# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_files/ui_startmenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(660, 645)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.img_main = QtWidgets.QLabel(Form)
        self.img_main.setObjectName("img_main")
        self.verticalLayout.addWidget(self.img_main)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pb_4 = QtWidgets.QPushButton(Form)
        self.pb_4.setObjectName("pb_4")
        self.horizontalLayout_2.addWidget(self.pb_4)
        self.pb_5 = QtWidgets.QPushButton(Form)
        self.pb_5.setObjectName("pb_5")
        self.horizontalLayout_2.addWidget(self.pb_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_1 = QtWidgets.QPushButton(Form)
        self.pb_1.setObjectName("pb_1")
        self.horizontalLayout.addWidget(self.pb_1)
        self.pb_2 = QtWidgets.QPushButton(Form)
        self.pb_2.setObjectName("pb_2")
        self.horizontalLayout.addWidget(self.pb_2)
        self.pb_3 = QtWidgets.QPushButton(Form)
        self.pb_3.setObjectName("pb_3")
        self.horizontalLayout.addWidget(self.pb_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "TaskCreator - main menu"))
        self.img_main.setText(_translate("Form", "TextLabel"))
        self.pb_4.setText(_translate("Form", "PushButton"))
        self.pb_5.setText(_translate("Form", "PushButton"))
        self.pb_1.setText(_translate("Form", "PushButton"))
        self.pb_2.setText(_translate("Form", "PushButton"))
        self.pb_3.setText(_translate("Form", "PushButton"))
